//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public interface IPlayer 
{
	void PlayMovie(string name, DateTime releaseDate, string website, string lengthInMinutes, Actor actors);
}


