//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Movie
{
	public virtual string Name
	{
		get;
		set;
	}

	public virtual int ReleaseDate
	{
		get;
		set;
	}

	public virtual string Website
	{
		get;
		set;
	}

	public virtual Actor Actors
	{
		get;
		set;
	}

	public virtual string LengthInMinutes
	{
		get;
		set;
	}

	public virtual Actor Actor
	{
		get;
		set;
	}

}

