//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Text;

public class NetflixPlayer : IPlayer
{
    public virtual void PlayMovie(string name, DateTime releaseDate, string website, string lengthInMinutes, Actor actors)
    {
        Debug.WriteLine("Star Wars 3", 2005, "http://www.imdb.com/starwars3", "112 minutes", "Peter Mayhew");
    }
}

