//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Text;

public class SFPlayer : IPlayer
{
    public void PlayMovie(string name, DateTime releaseDate, string website, string lengthInMinutes, Actor actors)
    {
        Debug.WriteLine("Mad Max", 2015, "http://www.imdb.com/madmax", "120 minutes", "Tom Hardy");
    }
}

